package LWS::HackDay::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'LWS::HackDay::Schema',
);

=head1 NAME

LWS::HackDay::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<LWS::HackDay>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<LWS::HackDay::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

Matthias Dietrich

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
